name: Docker

on:
  workflow_call:

jobs:

  docker:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest']
    steps:
    - uses: actions/checkout@v3

    - name: Setup Docker Build
      uses: docker/setup-buildx-action@v3.3.0

    - name: Docker Login
      uses: docker/login-action@v3.1.0
      with:
        username: pedroaccarini
        password: ${{ secrets.DOCKERPASS }}
            
